INSERT INTO address(city, `number`, street) VALUES('Hanoi','15','Duy Tan');
INSERT INTO address(city, `number`, street) VALUES('Hanoi','77','Huynh Thuc Khang');
INSERT INTO address(city, `number`, street) VALUES('Hanoi','400','Minh Khai');
INSERT INTO company(full_name, short_name) VALUES('FPT Software','fsoft');
INSERT INTO company(full_name, short_name) VALUES('CTIN','ctin');
INSERT INTO company(full_name, short_name) VALUES('VinAI','vai');
INSERT INTO contact_person (birth_of_date, name) VALUES ('1995-05-16','sa');
INSERT INTO contact_person (birth_of_date, name) VALUES ('1992-06-05','teo');
INSERT INTO contact_person (birth_of_date, name) VALUES ('1988-02-09','vi');
INSERT INTO phone(country_prefix, phone_number, sign) VALUES ('84','113','+');
INSERT INTO phone(country_prefix, phone_number, sign) VALUES ('84','115','+');
INSERT INTO phone(country_prefix, phone_number, sign) VALUES ('84','131','+');
INSERT INTO phone(country_prefix, phone_number, sign) VALUES ('84','654','+');
INSERT INTO phone(country_prefix, phone_number, sign) VALUES ('84','3213','+');

UPDATE address SET company_id=(select id from company where short_name='fsoft') WHERE street='Duy Tan';
UPDATE address SET company_id=(select id from company where short_name='ctin') WHERE street='Huynh Thuc Khang';
UPDATE address SET company_id=(select id from company where short_name='vai') WHERE street='Minh Khai';
UPDATE company SET address_id=(select id from address where street = 'Duy Tan'), contact_person_id=(select id from contact_person where name ='sa') WHERE short_name='fsoft';
UPDATE company SET address_id=(select id from address where street = 'Huynh Thuc Khang'), contact_person_id=(select id from contact_person where name ='teo') WHERE short_name='ctin';
UPDATE company SET address_id=(select id from address where street = 'Minh Khai'), contact_person_id=(select id from contact_person where name ='vi') WHERE short_name='vai';
UPDATE company SET address_id=2, contact_person_id=2 WHERE id=2;
UPDATE company SET address_id=3, contact_person_id=3 WHERE id=3;
UPDATE contact_person SET company_id=(select id from company where name='FPT Software') WHERE name='sa';
UPDATE contact_person SET company_id=(select id from company where name='CTIN') WHERE name='teo';
UPDATE contact_person SET company_id=(select id from company where name='VinAI') WHERE name='vi';
UPDATE phone SET contact_person_id=(select id from contact_person where name='sa') WHERE phone_number='113';
UPDATE phone SET contact_person_id=(select id from contact_person where name='sa') WHERE phone_number='115';
UPDATE phone SET contact_person_id=(select id from contact_person where name='teo') WHERE phone_number='131';
UPDATE phone SET contact_person_id=(select id from contact_person where name='sa') WHERE phone_number='654';
UPDATE phone SET contact_person_id=(select id from contact_person where name='vi') WHERE phone_number='3213';
